#
# $Id: Makefile,v 1.2 2010/05/25 00:00:00 root Exp $
#

G++	= g++
AR	= ar
CFLAGS	= -Wall -O2 -funroll-loops -fomit-frame-pointer
SRC	= libtta.cpp
LIB	= libtta

all:	$(SRC)
	$(G++) -c $(CFLAGS) $(SRC) -o $(LIB).o
	$(AR) rcs $(LIB).a $(LIB).o

clean:
	rm -f *.o *.lo *.a

